services:
  web:
    build: .
    container_name: copygram
    image: web
    restart: unless-stopped
    command: ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", 
              "copygram.asgi:application", "--bind", "0.0.0.0:8000",
              "--reload"]
    networks:
      - my_network
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    container_name: db
    restart: unless-stopped
    networks:
      - my_network
    volumes:
      - db-data:/var/lib/postgresql/data/
    env_file:
      - .env

  redis:
    image: redis:7.0
    container_name: redis
    networks:
      - my_network

  celery_worker:
    build: .
    container_name: worker
    image: celery_worker
    command: celery -A copygram worker -l info
    networks:
      - my_network
    volumes: 
      - .:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis
  
  celery_beat:
    build: .
    container_name: scheduler
    image: celery_beat
    command: ["celery", "-A", "copygram", 
              "beat", "-l", "info"]
    networks:
      - my_network
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - celery_worker

  nginx:
    image: nginx:1.25
    container_name: nginx
    restart: always
    networks:
      - my_network
    volumes:
      - ./nginx:/etc/nginx/templates
      - .:/app
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - "web"

networks:
  my_network:
    driver: bridge

volumes:
  db-data:
    driver: local
